version: '3.8'

services:
  flink-estimator:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: flink-estimator
    image: jbcodeforce/flink-estimator:latest
    ports:
      - "8000:8000"
    volumes:
      # Mount saved estimations as a volume for persistence
      - ./saved_estimations:/app/saved_estimations
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  saved_estimations:
    driver: local